from enum import IntEnum


class Command(IntEnum):
    """SerialAPI command IDs from ``vendor/serialAPI/core/core.h``.

    Members are deliberately sorted by their numeric wire value. Values that
    the vendored SerialAPI header does not assign are not invented here.
    ``CMD_CONFIRM`` and ``CMD_ERROR`` are board responses and are kept in
    :class:`ResponseCommand`.
    """

    # A SerialAPI-library wildcard, rather than a command sent to the board.
    ANY_SERIAL_COMMAND = 1

    CMD_BOARD_INFO_3 = 20
    CMD_READ_PARAMS_3 = 21
    CMD_WRITE_PARAMS_3 = 22
    CMD_REALTIME_DATA_3 = 23
    CMD_SELECT_IMU_3 = 24
    CMD_REALTIME_DATA_4 = 25
    CMD_ENCODERS_CALIB_OFFSET_4 = 26
    CMD_ENCODERS_CALIB_FLD_OFFSET_4 = 27
    CMD_READ_PROFILE_NAMES = 28
    CMD_WRITE_PROFILE_NAMES = 29
    CMD_QUEUE_PARAMS_INFO_3 = 30
    CMD_SET_ADJ_VARS_VAL = 31
    CMD_SAVE_PARAMS_3 = 32
    CMD_READ_PARAMS_EXT = 33
    CMD_WRITE_PARAMS_EXT = 34
    CMD_AUTO_PID = 35
    CMD_SERVO_OUT = 36
    CMD_BODE_TEST_START_STOP = 37
    CMD_I2C_WRITE_REG_BUF = 39
    CMD_I2C_READ_REG_BUF = 40
    CMD_WRITE_EXTERNAL_DATA = 41
    CMD_READ_EXTERNAL_DATA = 42
    CMD_READ_ADJ_VARS_CFG = 43
    CMD_WRITE_ADJ_VARS_CFG = 44
    CMD_API_VIRT_CH_CONTROL = 45
    CMD_ADJ_VARS_STATE = 46
    CMD_EEPROM_WRITE = 47
    CMD_EEPROM_READ = 48
    CMD_CALIB_INFO = 49
    CMD_SIGN_MESSAGE = 50
    CMD_BOOT_MODE_3 = 51
    CMD_SYSTEM_STATE = 52
    CMD_READ_FILE = 53
    CMD_WRITE_FILE = 54
    CMD_FS_CLEAR_ALL = 55
    CMD_AHRS_HELPER = 56
    CMD_RUN_SCRIPT = 57
    CMD_SCRIPT_DEBUG = 58
    CMD_CALIB_MAG = 59
    CMD_GET_ANGLES_EXT = 61
    CMD_READ_PARAMS_EXT2 = 62
    CMD_WRITE_PARAMS_EXT2 = 63
    CMD_GET_ADJ_VARS_VAL = 64
    CMD_CALIB_ACC = 65
    CMD_CALIB_BAT = 66
    CMD_CONTROL = 67
    CMD_REALTIME_DATA = 68
    CMD_EXECUTE_MENU = 69
    CMD_USE_DEFAULTS = 70
    CMD_CALIB_EXT_GAIN = 71
    CMD_HELPER_DATA = 72
    CMD_GET_ANGLES = 73
    CMD_CALIB_MOTOR_MAG_LINK = 74
    CMD_GYRO_CORRECTION = 75
    CMD_MODULE_LIST = 76
    CMD_MOTORS_ON = 77
    CMD_CALIB_OFFSET = 79
    CMD_CALIB_POLES = 80
    CMD_READ_PARAMS = 82
    CMD_TRIGGER_PIN = 84
    CMD_DATA_STREAM_INTERVAL = 85
    CMD_BOARD_INFO = 86
    CMD_WRITE_PARAMS = 87
    CMD_REALTIME_DATA_CUSTOM = 88
    CMD_BEEP_SOUND = 89
    CMD_CONTROL_CONFIG = 90
    CMD_CALIB_ORIENT_CORR = 91
    CMD_COGGING_CALIB_INFO = 92
    CMD_CALIB_COGGING = 93
    CMD_CALIB_ACC_EXT_REF = 94
    CMD_PROFILE_SET = 95
    CMD_CAN_DEVICE_SCAN = 96
    CMD_CAN_DRV_HARD_PARAMS = 97
    CMD_CAN_DRV_STATE = 98
    CMD_CAN_DRV_CALIBRATE = 99
    CMD_READ_RC_INPUTS = 100
    CMD_REALTIME_DATA_CAN_DRV = 101
    CMD_EVENT = 102
    CMD_CALIB_GYRO = 103
    CMD_READ_PARAMS_EXT3 = 104
    CMD_WRITE_PARAMS_EXT3 = 105
    CMD_EXT_IMU_DEBUG_INFO = 106
    CMD_SET_DEVICE_ADDR = 107
    CMD_AUTO_PID2 = 108
    CMD_MOTORS_OFF = 109
    CMD_EXT_IMU_CMD = 110
    CMD_READ_STATE_VARS = 111
    CMD_WRITE_STATE_VARS = 112
    CMD_SERIAL_PROXY = 113
    CMD_RESET = 114
    CMD_IMU_ADVANCED_CALIB = 115
    CMD_API_VIRT_CH_HIGH_RES = 116
    CMD_CALIB_ENCODER_LUT = 117
    CMD_CALIB_ENCODER_LUT_RES = 118
    CMD_WRITE_PARAMS_SET = 119
    CMD_CALIB_CUR_SENS = 120
    CMD_CONTROL_EXT = 121
    CMD_SYNC_MOTORS = 123
    CMD_CAN_DRV_TELEMETRY = 127
    CMD_EXT_MOTORS_ACTION = 128
    CMD_EXT_MOTORS_CONTROL = 129
    CMD_EXT_MOTORS_CONTROL_CONFIG = 130
    CMD_EXT_MOTORS_STATE = 131
    CMD_ADJ_VARS_INFO = 132
    CMD_SERVO_OUT_EXT = 133
    CMD_SET_ADJ_VARS_VAL_F = 134
    CMD_GET_ADJ_VARS_VAL_F = 135
    CMD_CONTROL_QUAT = 140
    CMD_CONTROL_QUAT_STATUS = 141
    CMD_CONTROL_QUAT_CONFIG = 142
    CMD_EXT_SENS_CMD = 150
    CMD_TRANSPARENT_SAPI = 151
    CMD_SET_DEBUG_PORT = 249
    CMD_MAVLINK_INFO = 250
    CMD_MAVLINK_DEBUG = 251
    CMD_DEBUG_VARS_INFO_3 = 253
    CMD_DEBUG_VARS_3 = 254


class ResponseCommand(IntEnum):
    """Commands that are sent by the board and must not be passed to execute."""

    CMD_CONFIRM = 67
    CMD_ERROR = 255


class MenuCommands(IntEnum):
    """Special codes for menu commands."""

    MENU_CMD_NO = 0
    MENU_CMD_PROFILE1 = 1
    MENU_CMD_PROFILE2 = 2
    MENU_CMD_PROFILE3 = 3
    MENU_CMD_SWAP_PITCH_ROLL = 4
    MENU_CMD_SWAP_YAW_ROLL = 5
    MENU_CMD_CALIB_ACC = 6
    MENU_CMD_RESET = 7
    MENU_CMD_SET_ANGLE = 8
    MENU_CMD_CALIB_GYRO = 9
    MENU_CMD_MOTOR_TOGGLE = 10
    MENU_CMD_MOTOR_ON = 11
    MENU_CMD_MOTOR_OFF = 12
    MENU_CMD_FRAME_UPSIDE_DOWN = 13
    MENU_CMD_PROFILE4 = 14
    MENU_CMD_PROFILE5 = 15
    MENU_CMD_AUTO_PID = 16
    MENU_CMD_LOOK_DOWN = 17
    MENU_CMD_HOME_POSITION = 18
    MENU_CMD_RC_BIND = 19
    MENU_CMD_CALIB_GYRO_TEMP = 20
    MENU_CMD_CALIB_ACC_TEMP = 21
    MENU_CMD_BUTTON_PRESS = 22
    MENU_CMD_RUN_SCRIPT1 = 23
    MENU_CMD_RUN_SCRIPT2 = 24
    MENU_CMD_RUN_SCRIPT3 = 25
    MENU_CMD_RUN_SCRIPT4 = 26
    MENU_CMD_RUN_SCRIPT5 = 27
    MENU_CMD_CALIB_MAG = 33
    MENU_CMD_LEVEL_ROLL_PITCH = 34
    MENU_CMD_CENTER_YAW = 35
    MENU_CMD_UNTWIST_CABLES = 36
    MENU_CMD_SET_ANGLE_NO_SAVE = 37
    MENU_CMD_HOME_POSITION_SHORTEST = 38
    MENU_CMD_CENTER_YAW_SHORTEST = 39
    MENU_CMD_ROTATE_YAW_180 = 40
    MENU_CMD_ROTATE_YAW_180_FRAME_REL = 41
    MENU_CMD_SWITCH_YAW_180_FRAME_REL = 42
    MENU_CMD_SWITCH_POS_ROLL_90 = 43
    MENU_CMD_START_TIMELAPSE = 44
    MENU_CMD_CALIB_MOMENTUM = 45
    MENU_CMD_LEVEL_ROLL = 46
    MENU_CMD_REPEAT_TIMELAPSE = 47
    MENU_CMD_LOAD_PROFILE_SET1 = 48
    MENU_CMD_LOAD_PROFILE_SET2 = 49
    MENU_CMD_LOAD_PROFILE_SET3 = 50
    MENU_CMD_LOAD_PROFILE_SET4 = 51
    MENU_CMD_LOAD_PROFILE_SET5 = 52
    MENU_CMD_LOAD_PROFILE_SET_BACKUP = 53
    MENU_CMD_INVERT_RC_ROLL = 54
    MENU_CMD_INVERT_RC_PITCH = 55
    MENU_CMD_INVERT_RC_YAW = 56
    MENU_CMD_SNAP_TO_FIXED_POSITION = 57
    MENU_CMD_CAMERA_REC_PHOTO_EVENT = 58
    MENU_CMD_CAMERA_PHOTO_EVENT = 59
    MENU_CMD_MOTORS_SAFE_STOP = 60
    MENU_CMD_CALIB_ACC_AUTO = 61
    MENU_CMD_RESET_IMU = 62
    MENU_CMD_FORCED_FOLLOW_TOGGLE = 63
    MENU_CMD_AUTO_PID_GAIN_ONLY = 64
    MENU_CMD_LEVEL_PITCH = 65
    MENU_CMD_MOTORS_SAFE_TOGGLE = 66
    MENU_CMD_TIMELAPSE_STEP1 = 67
    MENU_CMD_EXT_GYRO_ONLINE_CALIB = 68
    MENU_CMD_DISABLE_FOLLOW_TOGGLE = 69
    MENU_CMD_SET_CUR_POS_AS_HOME = 70
    MENU_CMD_STOP_SCRIPT = 71
    MENU_CMD_TRIPOD_MODE_OFF = 72
    MENU_CMD_TRIPOD_MODE_ON = 73
    MENU_CMD_SET_RC_TRIM = 74
    MENU_CMD_HOME_POSITION_MOTORS = 75
    MENU_CMD_RETRACTED_POSITION = 76
    MENU_CMD_SHAKE_GENERATOR_OFF = 77
    MENU_CMD_SHAKE_GENERATOR_ON = 78
    MENU_CMD_SERVO_MODE_ON = 79
    MENU_CMD_SERVO_MODE_OFF = 80
    MENU_CMD_SERVO_MODE_TOGGLE = 81
